root: true
env:
  browser: true
  commonjs: true
  es6: true
  mocha: true
  shared-node-browser: true
extends:
  - airbnb
  - airbnb/hooks
  - plugin:chai-expect/recommended
  - plugin:mocha/recommended
  - plugin:security/recommended
  - plugin:@typescript-eslint/recommended
  - prettier
  - prettier/react
  - prettier/@typescript-eslint
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
  Handshake: writable
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - chai-expect
  - chai-friendly
  - import
  - jsx-a11y
  - mocha
  - react
  - react-hooks
  - security
  - "@typescript-eslint"
settings:
  react:
    createClass: createReactClass
    pragma: React
    version: detect
  import/parsers:
    "@typescript-eslint/parser":
      - ".ts"
      - ".tsx"
      - ".d.ts"
  import/resolver:
    typescript:
      alwaysTryTypes: true
ignorePatterns:
  - dist/
  - generated/
  - vendor/
rules:
  # Mocha/Chai Compatability
  func-names: "off"
  no-unused-expressions: "off"
  mocha/no-mocha-arrows: "off"
  # TypeScript Compatability
  import/extensions:
    - error
    - ignorePackages
    - js: never
      mjs: never
      jsx: never
      ts: never
      tsx: never
  import/named: "off"
  import/namespace: "off"
  import/default: "off"
  import/no-named-as-default-member: "error"
  import/no-cycle: "off"
  no-undef: "off"
  "@typescript-eslint/explicit-function-return-type": "off"
  "@typescript-eslint/no-use-before-define": "off"
  # React rules
  react/jsx-filename-extension:
    - error
    - extensions:
        - .jsx
        - .tsx
  react/destructuring-assignment: "off"
  react/prop-types: "off"
  # Performance (let Prettier handle)
  indent: "off"
  "@typescript-eslint/indent": "off"
  # Handshake Rules
  import/order:
    - error
    - groups:
        - builtin
        - external
        - internal
        - unknown
        - parent
        - sibling
        - index
      newlines-between: always
  import/prefer-default-export: "off"
  no-console:
    - error
    - allow:
        - assert
        - clear
        - count
        - countReset
        - dir
        - dirxml
        - error
        - exception
        - group
        - groupCollapsed
        - groupEnd
        - profile
        - profileEnd
        - table
        - timetimeStamp
        - warn
  no-restricted-imports:
    - error
    - paths:
        - name: "react-bootstrap"
          importNames:
            - Accordion
            - Alert
            - Badge
            - Breadcrumb
            - BreadcrumbItem
            - Button
            - ButtonGroup
            - ButtonToolbar
            - Carousel
            - CarouselCaption
            - CarouselItem
            # - Checkbox
            - Clearfix
            - Col
            - Collapse
            # - ControlLabel
            # - Dropdown
            # - DropdownButton
            - DropdownMenu
            - DropdownToggle
            - Fade
            - Form
            # - FormControl
            - FormControlFeedback
            - FormControlStatic
            # - FormGroup
            - Glyphicon
            - Grid
            # - HelpBlock
            - Image
            # - InputGroup
            - InputGroupAddon
            - InputGroupButton
            - Jumbotron
            - Label
            - ListGroup
            - ListGroupItem
            - Media
            - MediaBody
            - MediaHeading
            - MediaLeft
            - MediaList
            - MediaListItem
            - MediaRight
            # - MenuItem
            - Modal
            - ModalBody
            - ModalDialog
            - ModalFooter
            - ModalHeader
            - ModalTitle
            - Nav
            - Navbar
            - NavbarBrand
            - NavbarCollapse
            - NavbarHeader
            - NavbarToggle
            - NavDropdown
            - NavItem
            # - Overlay
            # - OverlayTrigger
            - PageHeader
            - PageItem
            - Pager
            - PagerItem
            - Pagination
            - PaginationItem
            - Panel
            - PanelHeading
            - PanelTitle
            - PanelToggle
            - PanelCollapse
            - PanelBody
            - PanelFooter
            - PanelGroup
            # - Popover
            - ProgressBar
            # - Radio
            - ResponsiveEmbed
            - Row
            - SafeAnchor
            - SplitButton
            - SplitToggle
            - Tab
            - TabContainer
            - TabContent
            - Table
            - TabPane
            - Tabs
            - Thumbnail
            - ToggleButton
            - ToggleButtonGroup
            # - Tooltip
            - Well
            - utils
  # Temporary until fixed, grouped by namespace
  array-callback-return: warn # 26 pre-existing
  class-methods-use-this: warn # 151 pre-existing
  consistent-return: warn # 336 pre-existing
  default-case: warn # 43 pre-existing
  global-require: warn # 49 pre-existing
  max-classes-per-file: warn # 1 pre-existing
  new-cap: warn # 6 pre-existing
  no-alert: warn # 10 pre-existing
  no-async-promise-executor: warn # 1 pre-existing
  no-case-declarations: warn # 82 pre-existing
  no-continue: warn # 3 pre-existing
  no-empty-pattern: warn # 1 pre-existing
  no-fallthrough: warn # 2 pre-existing
  no-global-assign: warn # 2 pre-existing
  no-multi-str: warn # 7 pre-existing
  no-nested-ternary: warn # 35 pre-existing
  no-param-reassign: warn # 214 pre-existing
  no-plusplus: warn # 17 pre-existing
  no-prototype-builtins: warn # 7 pre-existing
  no-restricted-globals: warn # 35 pre-existing
  no-restricted-syntax: warn # 11 pre-existing
  no-return-assign: warn # 60 pre-existing
  no-script-url: warn # 2 pre-existing
  no-self-compare: warn # 4 pre-existing
  no-shadow: warn # 1456 pre-existing
  no-throw-literal: warn # 2 pre-existing
  no-underscore-dangle: warn # 43 pre-existing
  no-unreachable: warn # 6 pre-existing
  no-useless-concat: warn # 2 pre-existing
  no-useless-constructor: warn # 4 pre-existing
  no-useless-escape: warn # 73 pre-existing
  prefer-const: warn # 6 pre-existing
  prefer-promise-reject-errors: warn # 6 pre-existing
  vars-on-top: warn # 6 pre-existing
  chai-expect/missing-assertion: warn # 25 pre-existing
  chai-expect/no-inner-compare: warn # 5 pre-existing
  chai-expect/no-inner-literal: warn # 5 pre-existing
  chai-friendly/no-unused-expressions: warn # 97 pre-existing
  import/no-dynamic-require: warn # 1 pre-existing
  import/no-extraneous-dependencies: warn # 490 pre-existing
  import/no-mutable-exports: warn # 4 pre-existing
  jsx-a11y/accessible-emoji: warn # 22 pre-existing
  jsx-a11y/alt-text: warn # 28 pre-existing
  jsx-a11y/anchor-is-valid: warn # 52 pre-existing
  jsx-a11y/click-events-have-key-events: warn # 108 pre-existing
  jsx-a11y/control-has-associated-label: warn # 8 pre-existing
  jsx-a11y/iframe-has-title: warn # 3 pre-existing
  jsx-a11y/img-redundant-alt: warn # 1 pre-existing
  jsx-a11y/interactive-supports-focus: warn # 2 pre-existing
  jsx-a11y/label-has-associated-control: warn # 61 pre-existing
  jsx-a11y/mouse-events-have-key-events: warn # 2 pre-existing
  jsx-a11y/no-noninteractive-element-interactions: warn # 3 pre-existing
  jsx-a11y/no-noninteractive-tabindex: warn # 1 pre-existing
  jsx-a11y/no-static-element-interactions: warn # 104 pre-existing
  mocha/max-top-level-suites: warn # 27 pre-existing
  mocha/no-hooks-for-single-case: warn # 662 pre-existing
  mocha/no-identical-title: warn # 12 pre-existing
  mocha/no-nested-tests: warn # 3 pre-existing
  mocha/no-setup-in-describe: warn # 673 pre-existing
  mocha/no-sibling-hooks: warn # 1 pre-existing
  mocha/no-top-level-hooks: warn # 4 pre-existing
  react-hooks/exhaustive-deps: warn # 52 pre-existing
  react-hooks/rules-of-hooks: warn # 1 pre-existing
  react/button-has-type: warn # 29 pre-existing
  react/jsx-no-bind: warn # 23 pre-existing
  react/jsx-no-target-blank: warn # 38 pre-existing
  react/jsx-props-no-spreading: warn # 898 pre-existing
  react/no-access-state-in-setstate: warn # 55 pre-existing
  react/no-array-index-key: warn # 53 pre-existing
  react/no-children-prop: warn # 1 pre-existing
  react/no-danger: warn # 24 pre-existing
  react/no-did-update-set-state: warn # 4 pre-existing
  react/no-find-dom-node: warn # 7 pre-existing
  react/no-string-refs: warn # 1 pre-existing
  react/no-this-in-sfc: warn # 7 pre-existing
  react/no-unescaped-entities: warn # 184 pre-existing
  react/no-unused-state: warn # 39 pre-existing
  react/prefer-stateless-function: warn # 366 pre-existing
  react/sort-comp: warn # 916 pre-existing
  react/static-property-placement: warn # 13 pre-existing
  security/detect-non-literal-fs-filename: warn # 17 pre-existing
  security/detect-non-literal-regexp: warn # 23 pre-existing
  security/detect-non-literal-require: warn # 1 pre-existing
  security/detect-object-injection: warn # 619 pre-existing
  security/detect-unsafe-regex: warn # 2 pre-existing
  "@typescript-eslint/camelcase": warn # 1154 pre-existing
  "@typescript-eslint/no-empty-interface": warn # 288 pre-existing
  "@typescript-eslint/no-explicit-any": warn # 4294 pre-existing
  "@typescript-eslint/no-namespace": warn # 1 pre-existing
  "@typescript-eslint/no-non-null-assertion": warn # 1 pre-existing
  "@typescript-eslint/no-unused-vars": # 176 pre-existing
    - warn
    - ignoreRestSiblings: true
  "@typescript-eslint/no-var-requires": warn # 892 pre-existing
